In [1]:
import pandas as pd
import json

results = None
with open('../results/shaping_results.json', 'r') as f:
  results = json.load(f)
results = [r for sample in results for r in sample] # flatten
df = pd.DataFrame(results)

In [5]:
df.head()

             0
0      regret1
1      regret2
2         None
3         EPIC
4  Shaped EPIC

In [10]:
df.corr()

,regret1,regret2,None,EPIC,Shaped EPIC,Maximal Shaped EPIC
regret1,1.000000,-0.017169,-0.024223,0.032828,0.106250,0.042294
regret2,-0.017169,1.000000,-0.085023,-0.002315,-0.009832,0.000743
None,-0.024223,-0.085023,1.000000,0.179930,0.187526,-0.206596
EPIC,0.032828,-0.002315,0.179930,1.000000,0.134466,0.043636
Shaped EPIC,0.106250,-0.009832,0.187526,0.134466,1.000000,0.022333
Maximal Shaped EPIC,0.042294,0.000743,-0.206596,0.043636,0.022333,1.000000